### ISSUE TITLE
OBS 自动录制 2 连接失败

### ISSUE THREAD

**Issue by Shuyuxu211** [Souma-Sumire/ff14-overlay-vue#21]
悬浮窗日志为：
Info: OBS 自动录制: BrowserConsole: Uncaught (in promise) Error: Not connected (Source: https://souma.diemoe.net/ff14-overlay-vue/assets/vendor-9c3ca848.js, Line: 180)
Info: OBS 自动录制: BrowserConsole: Uncaught (in promise) Error: Server sent no subprotocol (Source: https://souma.diemoe.net/ff14-overlay-vue/assets/vendor-9c3ca848.js, Line: 180)

已确认呆萌ACT与OBS均为管理员启动，防火墙存在OBS规则，OBS版本为30.2.3，端口是默认4455；
使用佬的老版自动录制插件可以连接成功（同端口）。

**Comment by Souma-Sumire** [comment]
连接OBS相关的代码，两代是完全一样的

请提供更多细节与复现手段
