### ISSUE TITLE
时间轴加载异常，设置按钮不再可见

### ISSUE THREAD

**Issue by SitaNya** [Souma-Sumire/ff14-overlay-vue#22]
您好！首先感谢您的付出！

发现时间: 2024/11/21 21:00
问题描述:时间轴无法正常加载，设置按钮不可见
排查过程:

21:00，我与朋友们（大约4人）都发现时间轴界面无法正常加载，在【刷新悬浮窗】后1人恢复可以看到时间轴但无法看到设置按钮，其余3人未恢复，我显示【已加载0条时间轴】
我尝试将URL从
https://souma.diemoe.net/#/timeline
改为
https://souma.diemoe.net/ff14-overlay-vue/#/timeline
再次尝试刷新悬浮窗后，显示【已加载22条时间轴】，显示恢复正常，但仍然看不到设置按钮

![image](https://github.com/user-attachments/assets/d6aefb0a-79f1-45fe-986b-0ddd3ea351fb)

上图为解锁悬浮窗后，可以看到紫色的可移动界面，但无法在此看到设置用的紫色齿轮

我于11月20日晚11点使用确认此组件正常运作

**Comment by SitaNya** [comment]
我尝试过开关翻墙VPN，对此问题无改善

**Comment by Souma-Sumire** [comment]
你好，我决定删除此按钮，改用只用浏览器进行交互。
请使用浏览器访问此地址：https://souma.diemoe.net/ff14-overlay-vue/#/timelineSettings?OVERLAY_WS=ws://127.0.0.1:10501/ws

**Comment by Lynchlily** [comment]
个人通过浏览器交互的情况反馈~
分别使用呆萌和咖啡，在同一网络下开梯子和不开梯子的情况下测试，呆萌均可顺利访问网址并进行交互，但咖啡均未成功，停留在获取ACT数据阶段。

**Comment by SitaNya** [comment]
收到！

**Comment by Souma-Sumire** [comment]
> 个人通过浏览器交互的情况反馈~ 分别使用呆萌和咖啡，在同一网络下开梯子和不开梯子的情况下测试，呆萌均可顺利访问网址并进行交互，但咖啡均未成功，停留在获取ACT数据阶段。

咖啡是否启用了ACT WS SERVER呢，并且如果你2个ACT一起开，端口是会冲突的。

**Comment by SitaNya** [comment]
抱歉我可能还需要请求一些帮助，我在启动ACT WS SERVER后，我的时间轴数量变为0了……
我眼下没有最近的备份文件，您有什么好的建议吗，感谢

**Comment by SitaNya** [comment]
我有备份过一个完整的ACT客户端，那个客户端里还保存着我以前的所有内容，但现在没有设置按钮……我不知道如何导出我以前的数据了

**Comment by Souma-Sumire** [comment]
> 抱歉我可能还需要请求一些帮助，我在启动ACT WS SERVER后，我的时间轴数量变为0了…… 我眼下没有最近的备份文件，您有什么好的建议吗，感谢

嗯？？我在代码上已经尽量规避了用户设置被清空的惨剧，应该不会发生才对。。。

**Comment by SitaNya** [comment]
我也希望这不会发生……但很遗憾……

**Comment by Souma-Sumire** [comment]
> 我也希望这不会发生……但很遗憾……

是设置页面显示0，并且时间轴里面也显示是0了吗！？

**Comment by SitaNya** [comment]
是的……如果是导入的轴倒是无所谓，但我有一些手工制作的轴……

**Comment by Souma-Sumire** [comment]
> 我有备份过一个完整的ACT客户端，那个客户端里还保存着我以前的所有内容，但现在没有设置按钮……我不知道如何导出我以前的数据了

你先别急，可以恢复
用你以前的ACT：
![image](https://github.com/user-attachments/assets/5f8a7645-fc41-43aa-9c12-66d5d31916b9)
![image](https://github.com/user-attachments/assets/d4e91f34-5f7e-4e13-b884-623a8244ac77)

非常抱歉出现这种情况，我会重新审视代码的实现

**Comment by SitaNya** [comment]
您无需道歉，毕竟能用到这东西已经非常棒了，我按照图中想想办法！

**Comment by SitaNya** [comment]
非常奇怪，我确信我在今晚曾经用其它url刷出过22条数据，我会再尝试几次

**Comment by Souma-Sumire** [comment]
你关掉设置页面了吗？

**Comment by SitaNya** [comment]
是的，因为在关掉前我看到时间轴栏位显示了绿色的，类似保存成功语义的字样，但抱歉我没太记住具体写的什么

**Comment by SitaNya** [comment]
哦，已更新数据

**Comment by Souma-Sumire** [comment]
首先使得你在悬浮窗中可以看到有22条时间轴。
然后在点击devTool时，你需要切换到时间轴那个标签，在他里面点开才有，因为数据是分域名保存的。
![image](https://github.com/user-attachments/assets/d86509ef-4dfc-49fa-9741-4c197dc4ade6)

**Comment by Souma-Sumire** [comment]
从现在开始设置页面必须手动点击按钮，才会进行数据传递了。
同时悬浮窗本体在接受数据时也会进行检查，当有删除操作时，必须手动确认才可以接受数据。
由于cdn的存在，改动会在大约30分钟后生效。

**Comment by SitaNya** [comment]
理解了，我要尝试寻找那22条时间轴……但我估计有些困难了，毕竟现在已经归0，我会尝试重试几次，实在不行就再弄一遍嘛没啥大事，以后能确保安全就好，辛苦您啦！

**Comment by Souma-Sumire** [comment]
斯米马赛，感谢你

**Comment by SitaNya** [comment]
啊抱歉还得打扰下，我有了一个新的进展：我找到旧的ACT里的字符串了！非常棒！

可惜我将它复制出来后，在新版本中导入失败，报错为

TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function

您是否需要我提供整体字符串文件给您呢

**Comment by SitaNya** [comment]
哦太棒了！非常感谢您，我自己搞定了
我看到有些部分似乎是描述时间轴风格的，所以我把jsonArray取了出来，它生效了！
我现在没有任何问题了，非常感谢您的协助！

**Comment by Souma-Sumire** [comment]
> 啊抱歉还得打扰下，我有了一个新的进展：我找到旧的ACT里的字符串了！非常棒！
> 
> 可惜我将它复制出来后，在新版本中导入失败，报错为
> 
> TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
> 
> 您是否需要我提供整体字符串文件给您呢

我知道你解决了哦。
这里贴一下怎么替换，以便以后有人看到这个问题不知道该怎么办：拿到的字符串不可以直接在UI里导入，也应该跟拿到的时候一样，通过DEVTOOLS的存储-本地存储，找到key为timelines的值，把新的字符串手动粘进去。

**Comment by SitaNya** [comment]
是的，非常感谢您的协助，不过我不得不在最后提出一个小问题……

经过我3次重启电脑、act、浏览器之后，我确信【导出全部】按钮并没有生效，我认为这可能是因为我有相当多很长的（绝本）时间轴，因为在点击几次按钮后，页面显示了内存不足

恕我直言，我觉得导出到剪贴板里可能不完全是个好主意……

**Comment by SitaNya** [comment]
我不是大佬……咱们都是开发者嘛，而且实话说……我并不擅长前端开发，非常遗憾

如果是在后端开发中，重一点的我会使用缓存框架来尝试解决问题，轻一点的方式下……也许直接写文件会不会好一些？
因为在写文件的过程中，可以将多个json分步写到文件里，类似于seek那种实现。或者干脆写多个文件让玩家自行每个单独导入。这样的好处是一次只加载一条时间轴就可以了

毕竟作为用户来说，其实时间轴的风格这是几分钟就可以弄好的事情，只要轴本身没丢，一切就都好办

**Comment by SitaNya** [comment]
就好比我刚才传输的文件……它有203kb（其实这也不大啊……），日后成长到它的3-5倍大是肯定的

**Comment by SitaNya** [comment]
顺便提个小建议……我不知道js正则是不是有什么不同，但标准正则在跳转表达式中经常失效……

**Comment by SitaNya** [comment]
诚然这是我自己的问题……也许该找机会学学前端了……

**Comment by Souma-Sumire** [comment]
加入了一些压缩导出体积的办法，（在cdn缓存更新之后）你可以尝试一下是否还会卡死

**Comment by Lynchlily** [comment]
> > 个人通过浏览器交互的情况反馈~ 分别使用呆萌和咖啡，在同一网络下开梯子和不开梯子的情况下测试，呆萌均可顺利访问网址并进行交互，但咖啡均未成功，停留在获取ACT数据阶段。
> 
> 咖啡是否启用了ACT WS SERVER呢，并且如果你2个ACT一起开，端口是会冲突的。 并且ACT的悬浮窗里，要有timeline的本体并且启用了，才能通信成功。

 俺又重新试了下！都启用了ACT WS SERVER打开timeline，然后咖啡和呆萌分别开和不开梯子测试4次，每次都重启电脑，还是呆萌OK但是咖啡不可以，一直是“正在请求数据，请确保ACT与时间轴悬浮窗已开启...，若 3 秒内仍未获取到数据，请检查ACT状态，且确认 timeline 悬浮窗已开启”的状态，在NGA看到帖子好像也有相同情况的好兄弟

**Comment by Souma-Sumire** [comment]
> 俺又重新试了下！都启用了ACT WS SERVER打开timeline，然后咖啡和呆萌分别开和不开梯子测试4次，每次都重启电脑，还是呆萌OK但是咖啡不可以，一直是“正在请求数据，请确保ACT与时间轴悬浮窗已开启...，若 3 秒内仍未获取到数据，请检查ACT状态，且确认 timeline 悬浮窗已开启”的状态，在NGA看到帖子好像也有相同情况的好兄弟

我这里暂时无法复现你的问题，使用咖啡ACT、呆萌ACT都可以正常连接
另外测试时，不需要重启电脑。

**Comment by Lynchlily** [comment]
> > 俺又重新试了下！都启用了ACT WS SERVER打开timeline，然后咖啡和呆萌分别开和不开梯子测试4次，每次都重启电脑，还是呆萌OK但是咖啡不可以，一直是“正在请求数据，请确保ACT与时间轴悬浮窗已开启...，若 3 秒内仍未获取到数据，请检查ACT状态，且确认 timeline 悬浮窗已开启”的状态，在NGA看到帖子好像也有相同情况的好兄弟
> 
> 我这里暂时无法复现你的问题，使用咖啡ACT、呆萌ACT都可以正常连接 另外测试时，不需要重启电脑。

嘿嘿问题不大！先用呆萌，感谢大佬！

**Comment by SitaNya** [comment]
导出测试可用，现在不存在任何问题了，我准备关闭此issues，感谢您的支持！
