### ISSUE TITLE
从fflogs导入时间轴后无法进行编辑

### ISSUE THREAD

**Issue by cayde-6324** [Souma-Sumire/ff14-overlay-vue#23]
今天我发现设置按钮移除后用浏览器页面进行编辑，作为尝试我导入了一份巴哈姆特绝境战的logs。[链接](https://www.fflogs.com/reports/jvKQgNqZcn3MwH1G#fight=34&type=healing)
选择了骑士和一些减伤技能后，界面就变成了下图的样子
![图片](https://github.com/user-attachments/assets/af08a9cb-7eb5-49bf-92ec-12a582984a6f)
选择应用后刷新悬浮窗的确能看到时间轴数量+1，而且导出字符串再导入也能看见有正确数量的时间轴，但是浏览器确实看不到，尝试过重启ACT和重启电脑没有解决

**Comment by Souma-Sumire** [comment]
已修复（应该）
