### ISSUE TITLE
全副本与浏览威(Browsingway)兼容性问题

### ISSUE THREAD

**Issue by LittleNightmare** [Souma-Sumire/ff14-overlay-vue#7]
使用Y佬的浏览威，锁定窗口后，无法重新展开。浏览威里不能画动选择文字，下面的滚动栏又非常小。。。我拖动都失败了

已在其他窗口测试，证实单纯的锁定窗口不影响点击。尝试缩放窗口到150%，依然点击无响应

**Comment by Souma-Sumire** [comment]
由于错别字与逻辑跳跃比较多，我没有明白你的意思。

**Comment by LittleNightmare** [comment]
其实不管也没啥，今天测测原版act就弄个悬浮窗看看效果
